### ISSUE TITLE
Plugin errors out when the package does not exist

### ISSUE THREAD

**Issue by Ben10k** [lessthanoptimal/gversion-plugin#1]
I am using the plugin and I want the generated java class to be located in a package named generatedsources. This package does not exist when the project is checked out from git.

For example my config looks like this:
```
gversion {
    srcDir = "/main/src/main/java"
    classPackage = "lt.companyname.projectname.generatedsources"
    className = "Version"
    timeZone = "Europe/Vilnius"
}
```

I get an error message:
```
 java.io.FileNotFoundException: /location/of/project/projectname/main/src/main/java/lt/companyname/projectname/generatedsources/Version.java (No such file or directory)
```

I would like to be able to force a creation of the package directory.

**Comment by lessthanoptimal** [comment]
which version of gversion are you using?

**Comment by Ben10k** [comment]
I am using version 1.2.5 from https://plugins.gradle.org/m2/

**Comment by lessthanoptimal** [comment]
I was able to replicate the problem and it's fixed. Reopen the ticket if you have any problems. The new version is 1.2.6

**Comment by Ben10k** [comment]
Thank you for quick responses. I'll try the new version as soon as I can. If I'll encounter some problems I'll create a new issue.
