### ISSUE TITLE
Add a private constructor to hide the implicit public one

### ISSUE THREAD

**Issue by Ben10k** [lessthanoptimal/gversion-plugin#2]
When the class is generated it only has public static final constants and the class can be instantiated because it has an implicit public constructor.

Code quality tool SonarQube provides this explanation:
```
Utility classes, which are collections of static members, are not meant to be instantiated. Even abstract utility classes, which can be extended, should not have public constructors.

Java adds an implicit public constructor to every class which does not define at least one explicitly. Hence, at least one non-public constructor should be defined.
```

**Comment by lessthanoptimal** [comment]
I'll add it but just curious if this is only an issue because a validation tool is giving you a warning?

**Comment by Richardmbs3** [comment]
https://stackoverflow.com/questions/14398747/hide-utility-class-constructor-utility-classes-should-not-have-a-public-or-def

**Comment by lessthanoptimal** [comment]
done in v1.5.1
