### ISSUE TITLE
srcPath should be relative to project the plugin is applied to

### ISSUE THREAD

**Issue by ykrasik** [lessthanoptimal/gversion-plugin#3]
Hi,

I'm using this plugin in a multi-project setup. In my setup, this multi project repo hosts multiple projects with different versions each.
Currently, no matter which project I apply the plugin to, the version file is always generated relative to the root project instead of the project it's actually applied to, so I had to work around this:
`srcDir = project.rootDir.relativePath(project.file('src/main/kotlin')).normalize()`

However, I think it would make more sense that by default the srcDir would be relative to the project it's applied to.

**Comment by lessthanoptimal** [comment]
I agree and done. let me know if 1.5.0 works for you.

**Comment by ykrasik** [comment]
Works great, thanks!
