### ISSUE TITLE
Unparseable date: "%cI"

### ISSUE THREAD

**Issue by tjhu** [lessthanoptimal/gversion-plugin#4]
It works pretty well on my local Windows machine(with Git version 2.x). But when I ran it on my Linux server(with Git version 1.x), it failed.
> Execution failed for task ':createVersionFile'.
> java.text.ParseException: Unparseable date: "%cI"

My *build.gradle*
```
plugins {
    ...
    // For reading commit id
    id "com.peterabeles.gversion" version "1.5.0"
}
...
gversion {
    srcDir       = "src/main/java/"          
    classPackage = "com.my.package.name"
    className    = "GitVersion"              
    dateFormat   = "yyyy-MM-dd HH:mm:ss" 
    timeZone     = "America/Los_Angeles"                     
    debug        = false                      
    language     = "java"                   
    explicitType = false                      
}
...
project.compileJava.dependsOn(createVersionFile)
```

Here's the [stacktrace](https://github.com/lessthanoptimal/gversion-plugin/files/3225008/gateway.log)
It looks like it comes from here https://github.com/lessthanoptimal/gversion-plugin/blob/master/src/main/groovy/com/peterabeles/GVersion.groovy#L223. 

java version "1.8.0_181"
git version 1.8.3.1
CentOS Linux release 7.6.1810

**Comment by lessthanoptimal** [comment]
thanks for the detailed bug report. I'll work on replicating it when I get back from vacation. That should be in about two weeks.

**Comment by tjhu** [comment]
no worries. Enjoy your vacation!

**Comment by georgeakulov** [comment]
May be problem at
`static int[] parseGitVersion( String text ) `
because at my local repository 
```
> git version
git version 1.7.10.4

```
And version has 4 leksem

**Comment by lessthanoptimal** [comment]
sorry for taking so long. You guys probably came up with another solution! I believe this to be fixed and should work with an almost arbitrary number of leksem.  Version 1.5.2

**Comment by katelovescode** [comment]
I still get this issue when running gradle build inside Bitbucket Pipelines.  Any insight?

**Comment by lessthanoptimal** [comment]
@katelovescode I just noticed this comment from last year. If you're still willing, could you post the error message what what "git version" produces on Bitbucket?

**Comment by katelovescode** [comment]
> @katelovescode I just noticed this comment from last year. If you're still willing, could you post the error message what what "git version" produces on Bitbucket?

Sorry, I don't have access to the project anymore, it was for a client :(  If I run into it again, I'll let you know!
